spring.application.name=concert-booking-notification

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# SMTP — exemple avec Mailtrap/Gmail, à adapter
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.com.example.concert_booking_notification=DEBUG