spring.application.name=concert-booking-job

spring.datasource.url=jdbc:postgresql://localhost:5432/concert_booking
spring.datasource.username=postgres
spring.datasource.password=Mohamed123



spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

logging.level.com.example.concert_booking_job=DEBUG